# Generated by Django 3.2.9 on 2022-02-27 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webproj', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='content',
        ),
    ]
